In [1]:
from csrank import LetorRankingDiscreteChoiceDatasetReader
from csrank.util import setup_logging
import numpy as np

Using TensorFlow backend.


In [2]:
setup_logging(log_path="letordc.log")
ldc = LetorRankingDiscreteChoiceDatasetReader()

In [3]:
for y in ldc.Y_test[40]:
    if(np.all(y==0)):
        print(y)

In [4]:
from sklearn.preprocessing import LabelBinarizer
def convert_to_label_encoding(Y, n_objects):
    lb = LabelBinarizer().fit(np.arange(n_objects))
    return lb.transform(Y)

In [40]:
def sub_sampling_discrete_choices(Xt, Yt, n_objects=5):
    X_train = []
    Y_train = []
    bucket_size = int(Xt.shape[1]/n_objects)
    rs = np.random.RandomState(42 + n_objects)
    for x,y in zip(Xt, Yt):
        choices = np.append(np.where(y==1)[0], np.where(y==2)[0])
        zeros = np.delete(np.arange(0, Xt.shape[1]), choices)
        n = bucket_size
        if len(choices) > bucket_size:
            idx = rs.choice(choices, size=bucket_size, replace=False)
        else:
            idx = choices
        if(len(zeros)>n_objects-1):
            print("**************************************************************************************")
            idys = np.array([rs.choice(zeros, size=(n_objects-1), replace=False) for i in range(len(idx))])
            print(idx)
            print(idys)
            idx = np.append(idys, idx[:,None], axis=1)
            for i in idx:
                np.random.shuffle(i)
            print(idx)
            print(y[idx])
            print(np.argmax(y[idx], axis=1))
            print(y[choices])
            print("**************************************************************************************")
            if len(X_train) == 0:
                X_train = x[idx]
                Y_train = np.argmax(y[idx], axis=1)
            else:
                Y_train = np.concatenate([Y_train, np.argmax(y[idx], axis=1)], axis=0)
                X_train = np.concatenate([X_train, x[idx]], axis=0)
    return X_train, Y_train
x,y = sub_sampling_discrete_choices(ldc.X_test[40], ldc.Y_test[40], n_objects=10)
print(x.shape)
print(y.shape)

**************************************************************************************
[17  8  2 15]
[[39 19  0 38  7  6 34 35 37]
 [32  7 28  9 33 36  6 29 24]
 [19  6  9 35 34 31 10 39 33]
 [31 19 23 35  6 24 32  7 12]]
[[ 6 38 35 39 34  7 19 17 37  0]
 [24  7  6 29  8 33 32  9 28 36]
 [39 19  2 31 33  6 10 34 35  9]
 [12  6 19 15 32 35  7 31 23 24]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]
[7 4 2 3]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
**************************************************************************************
**************************************************************************************
[30  5  4 37]
[[34 17 32 12 14 31 19 26 35]
 [13  2 29 32  7  8 31 39 25]
 [13  7 14 33  2  8 17 25 39]
 [27 18 31 36 10 21 29  6 34]]
[[14 34 30 26 17 31 35 19 12 32]
 [ 8 29 39 32 13 25  2  5 31  7]
 [39  8  2 33  4 13 1

**************************************************************************************
[ 8 21 31]
[[35 27 17  4 15  7 32 38 22]
 [ 6 15 17  3 30 16 11  1 14]
 [33 26 20 28 10 11 17 36 30]]
[[38  4 22 17 27 32  8  7 35 15]
 [15  1  6 21 30 17 11 14  3 16]
 [33 30 36 20 10 31 17 26 28 11]]
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
[6 3 5]
[ 1.  1.  1.]
**************************************************************************************
**************************************************************************************
[ 9  7 22 29]
[[14 20 30 35  1 23 15 24 21]
 [15 18 21  0 12 34 33 20 11]
 [21 18 34 36 15  0 30 33 11]
 [31 13 14 34 23 12 36 37 20]]
[[ 9 15 35 30 24 14 21 20  1 23]
 [ 0 34 12 15  7 18 21 11 33 20]
 [33 15 36 34 18 22 21  0 30 11]
 [20 12 29 36 31 37 34 14 23 13]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  

**************************************************************************************
[34 27  9 12]
[[22  0  5 13  6 15 16 10 17]
 [ 6  0 18  5 15 13 23 22 17]
 [23  8 10 13 16 17 18  5 25]
 [ 8  7 22  0  4 15 20 13 23]]
[[ 0 22 13 16 34 10  6  5 15 17]
 [15 22  6 13 18 27  0  5 17 23]
 [23 10  8 25 16  9 17 13 18  5]
 [13 23 22  4  0 12 15 20  7  8]]
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
[4 5 5 5]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.]
**************************************************************************************
**************************************************************************************
[38  6]
[[22 13 26 14 36  8  2  3 17]
 [ 4 25 23 19 12 39  5 28 26]]
[[36 22 26  2 13 14 17 38  3  8]
 [19 23 39 28 25 26  4  5 12  6]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. 

In [4]:
for k in ldc.dataset_dictionaries["S1"].keys():
    f = np.array(ldc.dataset_dictionaries["S1"][k])[:,-1]
    if(np.all(f==0)):
        print(f)
        print(k)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
113
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
124
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
154
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.]
178
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
361
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [37]:
np.array(ldc.dataset_dictionaries["S2"]['1929'])[:,-1]

array([ 2.,  1.,  1.,  2.,  2.,  0.,  2.,  0.,  2.,  2.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  2.,  0.,  0.,  2.,  0.,  1.,  2.,  2.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  2.,  1.,  2.,  1.,  2.,  2.,  2.])

In [22]:
ldc.dataset_dictionaries["S2"].keys()

dict_keys(['1830', '1837', '1840', '1847', '1851', '1862', '1863', '1864', '1866', '1875', '1885', '1886', '1887', '1890', '1891', '1904', '1905', '1910', '1911', '1912', '1913', '1916', '1921', '1924', '1929', '1931', '1934', '1944', '1948', '1958', '1961', '1971', '1989', '2005', '2009', '2010', '2021', '2024', '2027', '2043', '2052', '2054', '2055', '2079', '2080', '2084', '2085', '2098', '2104', '2106', '2120', '2121', '2126', '2134', '2136', '2141', '2147', '2150', '2157', '2168', '2174', '2177', '2178', '2185', '2186', '2188', '2190', '2193', '2200', '2201', '2216', '2234', '2235', '2236', '2239', '2243', '2244', '2252', '2259', '2270', '2277', '2284', '2297', '2301', '2306', '2309', '2320', '2343', '2357', '2364', '2371', '2375', '2378', '2386', '2387', '2394', '2399', '2417', '2421', '2430', '2441', '2448', '2454', '2466', '2469', '2473', '2474', '2476', '2478', '2484', '2493', '2494', '2501', '2503', '2507', '2510', '2515', '2523', '2527', '2532', '2540', '2545', '2548', '2556